name:                potato-flow-vty
version:             0.1.0.0
github:              "pdlla/potato-flow-vty"
license:             BSD3
author:              "pdlla"
maintainer:          "chippermonky@gmail.com"
copyright:           "2020 Peter Lu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pdlla/potato-flow-vty#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
#- -Werror

default-extensions:
- ApplicativeDo
- BangPatterns
- DataKinds
- ConstraintKinds
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- relude
- reflex
- reflex-vty
- tinytools
- reflex-potatoes
- containers
- text
- vty
- time
- dependent-sum
- these
- extra
- lens
- constraints-extras
- semialign
- mtl
- data-default
- aeson
- ilist
- primitive
- http-conduit
- dependent-map
- aeson-pretty
- bytestring
- directory
- template-haskell
- reflex-test-host
- ref-tf
- bimap
- filepath
- ansi-terminal
- optparse-applicative
- clock
- file-embed

library:
  source-dirs: src

executables:
  potato-flow-vty-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - +RTS -A128m -n2m -s -RTS
    - -j
    - -O0
    dependencies:
    - potato-flow-vty

  write-term-width:
    main:                termwidth.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - potato-flow-vty

tests:
  potato-flow-vty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -j
    - -ddump-splices
    dependencies:
    - potato-flow-vty
    - HUnit
    - hspec
    - hspec-contrib
